eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}"
    register-with-eureka: true
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: user-service
              uri: lb://user-service
              filters:
                - AuthenticationFilter
                - ApiResponseTransformFilter
                - RewritePath=/api/v1/user/(?<segment>.*), /v1/$\{segment}
              predicates:
                - Path=/api/v1/user/**
  jackson:
    default-property-inclusion: non_null



server:
  port: 8005